import { editor as Editor } from "monaco-editor"

export const editorOptions: Editor.IEditorOptions = {
	fontFamily: "'Cascadia Code PL', Consolas, 'Courier New', monospace",
	fontSize: 15,
	renderFinalNewline: "on",
	stickyScroll: {
		enabled: true,
	},
	autoIndent: "full",
	automaticLayout: true,
	codeLens: true,
	colorDecorators: true,
	contextmenu: true,
	cursorBlinking: "expand",
	acceptSuggestionOnCommitCharacter: true,
	acceptSuggestionOnEnter: "on",
	accessibilitySupport: "auto",
	cursorSmoothCaretAnimation: "on",
	cursorStyle: "line",
	disableLayerHinting: false,
	disableMonospaceOptimizations: false,
	dragAndDrop: false,
	fixedOverflowWidgets: false,
	folding: true,
	foldingStrategy: "auto",
	fontLigatures: true,
	formatOnPaste: true,
	formatOnType: false,
	hideCursorInOverviewRuler: false,
	links: true,
	mouseWheelZoom: false,
	multiCursorMergeOverlapping: true,
	multiCursorModifier: "alt",
	overviewRulerBorder: true,
	overviewRulerLanes: 2,
	quickSuggestions: true,
	quickSuggestionsDelay: 100,
	readOnly: false,
	renderControlCharacters: false,
	renderLineHighlight: "all",
	renderWhitespace: "none",
	revealHorizontalRightPadding: 30,
	roundedSelection: true,
	rulers: [],
	scrollBeyondLastColumn: 5,
	scrollBeyondLastLine: false,
	selectOnLineNumbers: true,
	selectionClipboard: true,
	selectionHighlight: true,
	showFoldingControls: "mouseover",
	smoothScrolling: true,
	suggestOnTriggerCharacters: true,
	// eslint-disable-next-line
	wordSeparators: `~!@#$%^&*()-=+[{]}\|;:'",.<>/?`,
	wordWrap: "off",
	wordWrapBreakAfterCharacters: "\t})]?|&,;",
	wordWrapBreakBeforeCharacters: "{([+",
	wordWrapColumn: 80,
	wrappingIndent: "none",
	guides: {
		bracketPairs: true,
	},
}
